const autores = [
  "Abraham Lincoln",
  "Adam Phillips",
  "Adão Ventura",
  "Adélia Prado",
  "Adolfo Bioy Casares",
  "Adriana Falcão",
  "Adriano Espínola",
  "Affonso Ávila",
  "Alan Powers",
  "Alceu",
  "Álcman",
  "Alejandro Zambra",
  "Alexis de Tocqueville",
  "Alfred J. Keller",
  "Alison Bechdel",
  "Alix Barzelay",
  "Alphonsus de Guimaraens",
  "Ana Cristina Cesar",
  "Ana Estela de Sousa Pinto",
  "Anacreonte",
  "André Breton",
  "Anthony Browne",
  "Antoine de Saint-Exupéry",
  "Anton Tchekhov",
  "Antonio Cicero",
  "Aristófanes",
  "Aristóteles",
  "Armando Freitas Filho",
  "Ascenso Ferreira",
  "Asclepíades",
  "Augusto de Campos",
  "Augusto dos Anjos",
  "Augusto Meyer",
  "Banksy",
  "Baquílides",
  "Barbara Graziosi",
  "Benjamin Graham",
  "Benoist Simmat",
  "Bill Watterson",
  "Brian J. Robb",
  "Bruno Schulz",
  "Bryan Lee O'Malley",
  "C. S. Lewis",
  "Cacaso",
  "Calímaco",
  "CárcamO",
  "Carlito Azevedo",
  "Carlos Drummond de Andrade",
  "Carlos Nejar",
  "Carole Scott",
  "Carolina Moreyra",
  "Caroline Alexander",
  "Cecília Meireles",
  "Cesare Pavese",
  "Chacal",
  "Charles Dickens",
  "Charles Juliet",
  "Charles Perrault",
  "Chloé Legeay",
  "Chris Sidwells",
  "Clarice Lispector",
  "Claudia Roquette-Pinto",
  "Clifton Johnson",
  "Cormac McCarthy",
  "Craig Thompson",
  "Crinágoras",
  "Cyril Pedrosa",
  "Dan Jurgens",
  "Dani Choi",
  "Daniel Galera",
  "Dante Alighieri",
  "Dante Milano",
  "David Foster Wallace",
  "David Gilmour",
  "David Grann",
  "David Mazzucchelli",
  "David Merveille",
  "Davide Cali",
  "Dennis O\'Neil",
  "Dirce Waltrick do Amarante",
  "Dominique Ehrhard",
  "Dora Ferreira da Silva",
  "E. B. White",
  "E. T. A. Hoffmann",
  "Edgar Allan Poe",
  "Eiko Kadono",
  "Emílio Moura",
  "Emily Dickinson",
  "Empédocles",
  "Enrique Vila-Matas",
  "Ernst Jünger",
  "Esopo",
  "Ésquilo",
  "Estesícoro",
  "Eurípides",
  "F. Scott Fitzgerald",
  "Fábio Levatti",
  "Ferenc Molnár",
  "Ferreira Gullar",
  "Fiódor Dostoiévski",
  "Flávia Lins e Silva",
  "Flavia Mariano",
  "Francisco Alvim",
  "François Place",
  "Franz Kafka",
  "Frédéric Gros",
  "Frederick Douglass",
  "Frederico Lourenço",
  "Friedrich Nietzsche",
  "Gabriel García Márquez",
  "George Orwell",
  "Georges Bataille",
  "Gilka Machado",
  "Giovanna Zoboli",
  "Glauco Mattoso",
  "Gustave Flaubert",
  "Gustavo Duarte",
  "Hans Christian Andersen",
  "Haroldo de Campos",
  "Henriqueta Lisboa",
  "Henry David Thoreau",
  'Heródoto',
  "Hesíodo",
  "Hilda Hilst",
  "Hiromu Arakawa",
  "Homero",
  "I. F. Stone",
  "Íbico",
  "Italo Moriconi",
  "Ivan Gontcharóv",
  "Ivan Junqueira",
  "Ivan Pinheiro Machado",
  "Ivan Turguêniev",
  "J. R. R. Tolkien",
  "Jack London",
  "Jacob Grimm",
  "Jacob Pétry",
  "James Baldwin",
  "James Joyce",
  "James Madison",
  "James Wood",
  "João Cabral de Melo Neto",
  "Joaquim Cardozo",
  "Joe Sacco",
  "John Berger",
  "John Williams",
  "Jorge de Lima",
  "Jorge Luis Borges",
  "Jorge Wanderley",
  "Joseph Brodsky",
  "Joseph Mitchell",
  "Juan Carlos Onetti",
  "Julio Cortázar",
  "Junito de Souza Brandão",
  "Juta Bauer",
  "Kahlil Gibran",
  "Karl Ove Knausgard",
  "Laura Erber",
  'Lelis',
  "Lewis Carroll",
  "Liev Tolstói",
  "Lu Menezes",
  "Lucia Miguel Pereira",
  "Machado de Assis",
  "Manoel Caboclo",
  "Manoel de Barros",
  "Manuel Bandeira",
  "Mara Luquet",
  "Marcio Atalla",
  "Marcos Rey",
  "Maria Ângela Alvim",
  "Maria Nikolajeva",
  "Marilena Chaui",
  "Mário de Andrade",
  "Mário Faustino",
  "Mario Quintana",
  "Mario Vargas Llosa",
  "Mariza Ferrari",
  "Martin Luther King Jr.",
  "Maura Lopes Cançado",
  "Maurice Sendak",
  "Mauro Beting",
  "Max Beerbohm",
  "Monteiro Lobato",
  "Muriel Barbery",
  "Murilo Mendes",
  "Nastassja Martin",
  "Natsume Soseki",
  "Neil Philip",
  "Nikolai Gógol",
  "Olavo Bilac",
  "Olga Savary",
  "Oscar Wilde",
  "Oswald de Andrade",
  "Otto Lara Resende",
  "Ovídio",
  "P. L. Travers",
  "Pascal Thiercy",
  "Paulo Henriques Britto",
  "Paulo Leminski",
  "Paulo Mendes Campos",
  "Paulo Roberto Pires",
  "Pedro Kilkerry",
  "Pep Molist",
  "Peter Hunt",
  "Peter Sís",
  "Pierre Grimal",
  "Píndaro",
  "Piotr Socha",
  "Platão",
  "Possidipo",
  "Quino",
  "Rainer Maria Rilke",
  "Raja Mohanty",
  "Raul Bopp",
  "Raul Pompéia",
  "Raymond Queneau",
  "Ribeiro Couto",
  "Rick Riordan",
  "Robert Louis Stevenson",
  "Roberto Piva",
  "Rodolfo Walsh",
  "Rodrigo Garcia Lopes",
  "Rubem Braga",
  "Ruy Espinheira Filho",
  "Ryszard Kapuscinski",
  "Safo",
  "Sam Savage",
  "Sarah G. Rubin",
  "Sei Shônagon",
  "Sempé",
  "Shaun Tan",
  "Shel Silverstein",
  "Silvina Ocampo",
  "Simias de Rodes",
  "Simônides",
  "Sin-léqi-unnínni",
  "Sirish Rao",
  "Sófocles",
  "Sophie Van der Linden",
  "Stendhal",
  "Susan Sontag",
  "Suzy Lee",
  "Teócrito",
  "Thomas Bulfinch",
  "Thomas Jefferson",
  "Torquato Neto",
  "Truman Capote",
  "Ursula K. Le Guin",
  "Victor Hugo",
  "Vinicius de Moraes",
  "Virginia Woolf",
  "Waly Salomão",
  "Werner Jaeger",
  "Wilhelm Grimm",
  "William Hazlitt",
  "William J. Bennett",
  "William Shakespeare",
  "Wojciech Grajkowski",
  "Yasunari Kawabata",
  "Zila Mamede",
  "Ziraldo"
];

// Exibir a quantidade de autores
//document.getElementById('total-autores').innerHTML = autores.length;

console.log(autores.length);