const autores = [
  "Adam Phillips",
  "Adolfo Bioy Casares",
  "Adriana Falcão",
  "Alan Powers",
  "Alceu",
  "Álcman",
  "Alejandro Zambra",
  "Alfred J. Keller",
  "Alison Bechdel",
  "Alix Barzelay",
  "Ana Estela de Sousa Pinto",
  "Anacreonte",
  "André Breton",
  "Anthony Browne",
  "Anton Tchekhov",
  "Aristófanes",
  "Asclepíades",
  "Baquílides",
  "Benjamin Graham",
  "Benoist Simmat",
  "Bill Watterson",
  "Brian J. Robb",
  "Bruno Schulz",
  "Bryan Lee O'Malley",
  "Calímaco",
  "CárcamO",
  "Carlos Drummond de Andrade",
  "Carole Scott",
  "Carolina Moreyra",
  "Caroline Alexander",
  "Cesare Pavese",
  "Charles Juliet",
  "Charles Perrault",
  "Chloé Legeay",
  "Chris Sidwells",
  "Clarice Lispector",
  "Cormac McCarthy",
  "Craig Thompson",
  "Crinágoras",
  "Cyril Pedrosa",
  "Dan Jurgens",
  "Dani Choi",
  "Daniel Galera",
  "Dante Alighieri",
  "David Foster Wallace",
  "David Gilmour",
  "David Grann",
  "David Mazzucchelli",
  "David Merveille",
  "Davide Cali",
  "Dennis O\'Neil",
  "Dirce Waltrick do Amarante",
  "Dominique Ehrhard",
  "Edgar Allan Poe",
  "Eiko Kadono",
  "Empédocles",
  "Enrique Vila-Matas",
  "Ernst Jünger",
  "Esopo",
  "Ésquilo",
  "Estesícoro",
  "Eurípides",
  "Ferenc Molnár",
  "Fiódor Dostoiévski",
  "Flávia Lins e Silva",
  "Flavia Mariano",
  "Francisco Alvim",
  "François Place",
  "Franz Kafka",
  "Frédéric Gros",
  "Friedrich Nietzsche",
  "Gabriel García Márquez",
  "George Orwell",
  "Georges Bataille",
  "Giovanna Zoboli",
  "Gustave Flaubert",
  "Gustavo Duarte",
  "Henry David Thoreau",
  'Heródoto',
  "Hesíodo",
  "Homero",
  "I. F. Stone",
  "Íbico",
  "Italo Moriconi",
  "Ivan Gontcharóv",
  "Ivan Pinheiro Machado",
  "Ivan Turguêniev",
  "J. R. R. Tolkien",
  "Jack London",
  "Jacob Pétry",
  "James Joyce",
  "James Wood",
  "Jennifer Uman",
  "Joe Sacco",
  "John Berger",
  "John Williams",
  "Jorge Luis Borges",
  "Joseph Brodsky",
  "Joseph Mitchell",
  "Juan Carlos Onetti",
  "Julio Cortázar",
  "Junito de Souza Brandão",
  "Juta Bauer",
  "Kahlil Gibran",
  "Karl Ove Knausgard",
  "Laura Erber",
  "Lewis Carroll",
  "Liev Tolstói",
  "Lucia Miguel Pereira",
  "Machado de Assis",
  "Manuel Bandeira",
  "Mara Luquet",
  "Marcio Atalla",
  "Marcos Rey",
  "Maria Nikolajeva",
  "Marilena Chaui",
  "Mario Quintana",
  "Mario Vargas Llosa",
  "Mariza Ferrari",
  "Maura Lopes Cançado",
  "Maurice Sendak",
  "Mauro Beting",
  "Max Beerbohm",
  "Natsume Soseki",
  "Neil Philip",
  "Nikolai Gógol",
  "Otto Lara Resende",
  "P. L. Travers",
  "Pascal Thiercy",
  "Paulo Roberto Pires",
  "Pep Molist",
  "Peter Hunt",
  "Peter Sís",
  "Pierre Grimal",
  "Píndaro",
  "Possidipo",
  "Quino",
  "Rainer Maria Rilke",
  "Raja Mohanty",
  "Raul Pompéia",
  "Raymond Queneau",
  "Rick Riordan",
  "Robert Louis Stevenson",
  "Rodolfo Walsh",
  "Rubem Braga",
  "Ryszard Kapuscinski",
  "Safo",
  "Sam Savage",
  "Sarah G. Rubin",
  "Sei Shônagon",
  "Sempé",
  "Shaun Tan",
  "Shel Silverstein",
  "Silvina Ocampo",
  "Simias de Rodes",
  "Simônides",
  "Sin-léqi-unnínni",
  "Sirish Rao",
  "Sófocles",
  "Sophie Van der Linden",
  "Stendhal",
  "Susan Sontag",
  "Suzy Lee",
  "Thomas Bulfinch",
  "Truman Capote",
  "Valerio Vidali",
  "Victor Hugo",
  "Virginia Woolf",
  "Werner Jaeger",
  "William Hazlitt",
  "William J. Bennett",
  "Yasunari Kawabata",
  "Ziraldo"
];

// Exibir a quantidade de autores
document.getElementById('total-autores').innerHTML = autores.length;