const autores = [
  "Adam Phillips",
  "Alceu",
  "Álcman",
  "Alejandro Zambra",
  "Alison Bechdel",
  "Alix Barzelay",
  "Anacreonte",
  "André Breton",
  "Anthony Browne",
  "Aristófanes",
  "Asclepíades",
  "Baquílides",
  "Benoist Simmat",
  "Bill Watterson",
  "Bryan Lee O'Malley",
  "Calímaco",
  "CárcamO",
  "Carolina Moreyra",
  "Cesare Pavese",
  "Charles Juliet",
  "Charles Perrault",
  "Chloé Legeay",
  "Craig Thompson",
  "Crinágoras",
  "Cyril Pedrosa",
  "Dan Jurgens",
  "Dani Choi",
  "Dante Alighieri",
  "David Mazzucchelli",
  "David Merveille",
  "Davide Cali",
  "Dominique Ehrhard",
  "Empédocles",
  "Esopo",
  "Ésquilo",
  "Estesícoro",
  "Eurípides",
  "Fiódor Dostoiévski",
  "Flávia Lins e Silva",
  "François Place",
  "Frédéric Gros",
  "Friedrich Nietzsche",
  "Georges Bataille",
  "Giovanna Zoboli",
  "Gustave Flaubert",
  "Gustavo Duarte",
  'Heródoto',
  "Hesíodo",
  "Homero",
  "Íbico",
  "Jack London",
  "James Joyce",
  "Jennifer Uman",
  "Joe Sacco",
  "John Berger",
  "Joseph Brodsky",
  "Joseph Mitchell",
  "Juta Bauer",
  "Laura Erber",
  "Liev Tolstói",
  "Lucia Miguel Pereira",
  "Maurice Sendak",
  "Max Beerbohm",
  "Nikolai Gógol",
  "P. L. Travers",
  "Paulo Roberto Pires",
  "Pep Molist",
  "Píndaro",
  "Possidipo",
  "Quino",
  "Raja Mohanty",
  "Safo",
  "Shaun Tan",
  "Shel Silverstein",
  "Simias de Rodes",
  "Simônides",
  "Sin-léqi-unnínni",
  "Sirish Rao",
  "Sófocles",
  "Suzy Lee",
  "Valerio Vidali",
  "Virginia Woolf",
  "William Hazlitt",
  "Yasunari Kawabata"
];

// Exibir a quantidade de autores
document.getElementById('total-autores').innerHTML = autores.length;